### ISSUE TITLE
not supporting special characters / symbols

### ISSUE THREAD

**Issue by DiniMuetter85** [Bermos/Plex-bulk-downloader#8]
the pluging wouldn't start if there are some special characters / symbols in the description. here an example of an anime series:
.hack//SIGN
![2021-01-25 18_15_49-Plex](https://user-images.githubusercontent.com/57333849/105740326-64920d80-5f39-11eb-8f90-72a4e90a6052.png)

**Comment by Bermos** [comment]
I updated the extension so that it would replace dots in the directory path for the download. [Windows](https://docs.microsoft.com/en-gb/windows/win32/fileio/naming-a-file?redirectedfrom=MSDN) seems to dislike dots somehow.

Also I had to re-apply my extension to be able to update it so I can't really tell when the update will be published.
